version: "3.3"
services:
  nginx:
    image: testproject-nginx:0.1
    ports:
      - "8080:8080"
    container_name: testporject-nginx
  testproject-blue:
    image: testproject:0.1
    ports:
      - "8081:9090"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=blue
    container_name: testproject-blue
  testproject-green:
    image: testproject:0.1
    ports:
      - "8082:9090"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=green
    container_name: testproject-green